### ISSUE TITLE
any chance of some documentation?

### ISSUE THREAD

**Issue by aspiers** [defaultxr/PianoRoll#1]
Hi, thanks for sharing this!  Any chance it could be documented, even briefly?  I'd love to try it out but it's hard to know where to start ...  Thanks!

**Comment by defaultxr** [comment]
Sure, I'll try to update the repo and write some actual text in the readme sometime today. I don't really use sclang anymore but I'll make sure this is still working and give examples of usage and such.

**Comment by aspiers** [comment]
That would be great - thanks a lot!

**Comment by defaultxr** [comment]
OK, I've updated the class, wrote up a real readme, and updated/uploaded the requirements as well. I checked it and it seems to be working for me, but if you notice any issues, feel free to let me know.

**Comment by aspiers** [comment]
That's extremely helpful - thanks again!
